New log file opened at Mon May 30 10:12:09 PDT 2016 by 642@Madhus.local
Taking next connection to: 56941
New client attempting to connect on port: 56942-56941
  Address = /192.168.1.232:56941
This client on port 56942 has uuid ff504e7c-1914-40a2-8e99-879f1f1d7652 configName activator humanReadableName Activator protocolVersion 3 featureTags Vector()
Connected Clients: activator-ff504e7c-1914-40a2-8e99-879f1f1d7652
Taking next connection to: 56941
New client attempting to connect on port: 56943-56941
  Address = /192.168.1.232:56941
Handshake exception on socket: 56943
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:209)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at java.io.DataInputStream.readInt(DataInputStream.java:387)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 56941
New client attempting to connect on port: 56944-56941
  Address = /192.168.1.232:56941
This client on port 56944 has uuid 923aa7ad-d11a-4ece-b421-40b4a4f4be5b configName activator humanReadableName Activator protocolVersion 3 featureTags Vector()
Connected Clients: activator-ff504e7c-1914-40a2-8e99-879f1f1d7652, activator-923aa7ad-d11a-4ece-b421-40b4a4f4be5b
Taking next connection to: 56941
New client attempting to connect on port: 57107-56941
  Address = /192.168.1.232:56941
Handshake exception on socket: 57107
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readInt(DataInputStream.java:392)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 56941
New client attempting to connect on port: 57108-56941
  Address = /192.168.1.232:56941
This client on port 57108 has uuid 9ee0a16d-398d-4f5e-903a-b1abb87d72bb configName play-fork-run humanReadableName Play Fork Run protocolVersion 1 featureTags Vector()
Connected Clients: activator-923aa7ad-d11a-4ece-b421-40b4a4f4be5b, play-fork-run-9ee0a16d-398d-4f5e-903a-b1abb87d72bb
Taking next connection to: 56941
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 56941
